### ISSUE TITLE
Datafiles try to guess appropriate box from files, dataset or experiment, supersedes storagebox defaults

### ISSUE THREAD

**Issue by aswinnarayanan** [mytardis/mytardis#1792]
tardis/tardis_portal/models/datafile.py

get_default_storage_box  in Datafile class priorities guesses from dataset and experiment over the get_default_storage in the StorageBox class.

This leads to inconsistent behaviour - first datafile undergoes different storagebox assignment process compared to the subsequent files. This is problematic for setups where the server moves files around after upload.

Maybe the storagebox defaults should supersede the dataset/experiment guess, or allow the dataset/experiment guess to be disabled in settings (I have tried this option here https://github.com/aswinnarayanan/mytardis/commit/85b0de47b32e95cab31d44d8cedd642400e56b96)

**Comment by jameswettenhall** [comment]
Ah, thanks for raising this.  I didn't fully understand the issue when you raised it over Zoom, but now I do understand, and I agree that the logic to try to automatically store new DataFiles in the same storage box as other DataFiles in the same dataset can be unhelpful and confusing, e.g. when files are moved into a different storage box after upload.

**Comment by jameswettenhall** [comment]
Thanks for pointing us to your branch and feel free to submit a Pull Request from it.

Your changes look good and would appear to have zero risk of breaking anything for us.

The only thing we're wondering about is whether we can think of a better name for the new `GUESS_STORAGE_BOX` setting.

There are two ways to look at this.  On one hand, having too many settings can be confusing, so if we think most/all MyTardis users would be happy for this "guessing" logic to be removed at some point, then it would be better to deprecate it, in which case the `GUESS_STORAGE_BOX` setting might just be a temporary thing which raises a deprecation warning when `settings.GUESS_STORAGE_BOX==True` until the guessing code is removed.

But I think it's more likely that we'll want to keep some of the "guessing" code for now but make it optional, similar to what you have suggested.

I certainly don't see any value in trying to add new DataFileObjects to the same storage box as other DataFileObjects for the same DataFile record, so this code can almost certainly be removed:
```
            boxes_used = StorageBox.objects.filter(file_objects__datafile=self)
            if boxes_used:
                return boxes_used[0]
```

And I would also question the value of trying to re-use the storage box associated with the experiment, so maybe this code can be removed too:
```
        experiment_boxes = StorageBox.objects.filter(
            file_objects__datafile__dataset__experiments__in=self
            .dataset.experiments.all())
        if experiment_boxes:
            return experiment_boxes[0]
```

But I can see some value in reusing a dataset's storage box if it uses only one storage box, e.g.
```
            if settings.REUSE_DATASET_STORAGE_BOX:
                dataset_boxes = self.dataset.get_all_storage_boxes_used().distinct()
                if dataset_boxes.count() == 1:
                    return dataset_boxes[0]
```

The `distinct()` was only necessary in the above code snippet because it is missing from the `get_all_storage_boxes_used` method in `tardis/tardis_portal/models/dataset.py`.

Then the `REUSE_DATASET_STORAGE_BOX` setting could be documented as:
```
REUSE_DATASET_STORAGE_BOX = True
'''
If a new DataFile is created in a Dataset whose files are all stored in the same storage box,
then the new file will be stored in the same storage box, irrespective of the "default"
StorageBoxAttribute.
'''
```

**Comment by aswinnarayanan** [comment]
I am happy with all the suggested changes and with those changes REUSE_DATASET_STORAGE_BOX would be the more suitable name.

Also, if datasets are assigned storagebox in a future update (I think this was the case at some point before), REUSE_DATASET_STORAGE_BOX  would be more fitting and wouldn't need to change either.

Should I add them in and send a pull request?

**Comment by jameswettenhall** [comment]
Hi @aswinnarayanan, it would be great if you have time to put this in a pull request.  I would see value in doing it myself when I have time, but it will probably get moving more quickly if you submit the PR.

The only thing I started questioning after my last post, is whether the docstring explanation I gave for the `REUSE_DATASET_STORAGE_BOX` setting should also make a reference to what the `mytardis-app-mydata` app does, i.e. it looks for an approved storage box assigned to the `Uploader` instance i.e. the MyData instance: https://github.com/mytardis/mytardis-app-mydata/blob/master/api.py#L532
