### ISSUE TITLE
Preview image and count not updated after upload

### ISSUE THREAD

**Issue by steveandroulakis** [mytardis/mytardis#258]
If users upload using the 'standard' uploadify "Select Files" or filepicker.io interface, the added datafiles show up in the interface when done (without page refresh).

However the file count or preview images (if any) aren't updated.

**Comment by wettenhj** [comment]
The uploadify and filepicker.io interfaces are no longer the 'standard' upload methods - MyTardis currently uses the jQuery File Upload plugin maintained by blueimp (Sebastian Tschan).

The file count is now updated when files are uploaded, implemented in this commit: https://github.com/mytardis/mytardis/commit/7176a73256903fa04005696bcc55074d294746bc

Preview images are not expected to be updated immediately, as they should be generated asynchronously.  In future, MyTardis will offer better support for asynchronous-but-high-priority tasks by making it easier to route some of MyTardis's common asynchronous tasks to high-priority queues.  But I'm going to close this issue as the file count updating is done and because the issue refers to upload methods which are no longer commonly used in MyTardis (uploadify and filepicker.io).
