### ISSUE TITLE
Do we need both datafile_hook and dfo_hook in filter/__init__.py?

### ISSUE THREAD

**Issue by wettenhj** [mytardis/mytardis#473]
From the history, it looks like POST_SAVE filters were originally done just on Dataset_Files, not Replicas / DFOs.

Then from this commit onwards: https://github.com/mytardis/mytardis/commit/5faedfcf931d6c18ad4290646cee72fbbe54d890

the POST_SAVE filters were done on both Dataset_Files and Replicas, but it was noted in that commit comment that "we no longer get a Dataset_File save when we've successfully uploaded the file content (and verified)", so the result of that commit was apparently that only the replica_hook would be used, not the datafile_hook.

Is this assumption still correct, that once a datafile has been verified, only the DataFileObject will be saved, not the DataFile?  I'm trying to avoid having POST_SAVE filters fire more than once in quick succession.

**Comment by grischa** [comment]
Since we don't have a clear definition of what filters select their actions on and what they are supposed or allowed to do, we can't assume at this stage that they should only run in one or the other case.
Long term let's design a filter framework with a way to define triggers per filter.
Short term, making sure filters can run multiple times safely is a good idea anyway, see #471
