### ISSUE TITLE
API's ACLAuthorization read_list method should always return a QuerySet, not a list

### ISSUE THREAD

**Issue by wettenhj** [mytardis/mytardis#597]
In api.py, the ACLAuthorization class has a read_list method with a case for each model type.  For some model types, it returns a list, rather than a QuerySet, e.g. `[ds for ds in object_list if has_dataset_access(bundle.request, ds.id)]`, which means that enabling ordering for that model resource is not possible, because ordering is applied after the authorization check, leading to 

`AttributeError: 'list' object has no attribute 'order_by'`

Enabling ordering on specific fields should be as simple as enabling filtering on those fields, e.g.

```
class DatasetResource(MyTardisModelResource):
    ...
    class Meta(MyTardisModelResource.Meta):
        ...
        ordering = [
            'description'
        ]
```

**Comment by grischa** [comment]
Easily done, though a waste of resources, really:
`return Dataset.objects.filter(id__in=[ds.id for ds in object_list if has_dataset_access(bundle.request, ds.id)])`
Alternatively, we need a way to turn has_perm lookups into SQL queries (`Q`) and bubble them up into the API to be applied onto the object_list. Since we are looking to ditch tastypie eventually, maybe not worth the effort
